---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: Login user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: login successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
