default: &default
  adapter: postgresql
  encoding: unicode

  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  adapter: postgresql
  encoding: unicode
  database: college_management_development
  username: postgres
  password: password
  host: db
  pool: 5


test:
  <<: *default
  database: college_management_api_test


production:
  primary: &primary_production
    <<: *default
    database: college_management_api_production
    username: college_management_api
    password: <%= ENV["COLLEGE_MANAGEMENT_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: college_management_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: college_management_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: college_management_api_production_cable
    migrations_paths: db/cable_migrate
