source "https://rubygems.org"

gem "redis", ">= 4.0.1"
gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "rack-cors"
gem "kaminari"
gem "sidekiq"
gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
gem "image_processing", "~> 1.2"
group :development, :test do
  gem "factory_bot_rails"
  gem "rspec-rails", "~> 6.0.0"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
